# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_code', models.IntegerField()),
                ('certification', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50, null=True)),
                ('issuing_body', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('topic', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='certifications.Certification')),
            ],
        ),
    ]
